defaults:
  vendor: "ZTE"
  model: "C320"

  base_oids:
    oid_1082: ".1.3.6.1.4.1.3902.1082"
    oid_1012: ".1.3.6.1.4.1.3902.1012"
    oid_1015: ".1.3.6.1.4.1.3902.1015"

  system_oids:
    sys_descr: ".1.3.6.1.2.1.1.1.0"
    sys_uptime: ".1.3.6.1.2.1.1.3.0"
    sys_name: ".1.3.6.1.2.1.1.5.0"
    cpu_usage: ".2.1.3.9.2.1.3.1.1.3"
    memory_used: ".10.10.2.1.6.1.4.1.1.2"
    memory_free: ".10.10.2.1.6.1.4.1.1.3"
    temperature: ".10.10.2.1.6.1.2.1.1.2"
    olt_rx_power_base: ".1010.11.2.1.2"

  onu_oids:
    oid_1082:
      onu_id_name: ".500.10.2.3.3.1.2"
      onu_serial_number: ".500.10.2.3.3.1.18"
      onu_rx_power: ".500.20.2.2.2.1.10"
      onu_status_id: ".500.10.2.3.8.1.4"
      onu_description: ".500.10.2.3.3.1.3"
      onu_last_online_time: ".500.10.2.3.8.1.5"
      onu_last_offline_time: ".500.10.2.3.8.1.6"
      onu_last_offline_reason: ".500.10.2.3.8.1.7"
      onu_optical_distance: ".500.10.2.3.10.1.2"

    oid_1012:
      onu_type: ".3.50.11.2.1.17"
      onu_tx_power: ".3.50.12.1.1.14"
      onu_ip_address: ".3.50.16.1.1.10"

  boards:
    - slot: 1
      type: "GTGH" 
      pons:
        - pon_id: 1  # 1082 index + 1012 index
          enabled: true
          ifindex_1082: 285278465
          ifindex_1012: 268501248
        - pon_id: 2
          enabled: true
          ifindex_1082: 285278466
          ifindex_1012: 268501504
        - pon_id: 3
          enabled: true
          ifindex_1082: 285278467
          ifindex_1012: 268501760
        - pon_id: 4
          enabled: true
          ifindex_1082: 285278468
          ifindex_1012: 268502016
        - pon_id: 5
          enabled: true
          ifindex_1082: 285278469
          ifindex_1012: 268502272
        - pon_id: 6
          enabled: true
          ifindex_1082: 285278470
          ifindex_1012: 268502528
        - pon_id: 7
          enabled: true
          ifindex_1082: 285278471
          ifindex_1012: 268502784
        - pon_id: 8
          enabled: true
          ifindex_1082: 285278472
          ifindex_1012: 268503040
        - pon_id: 9
          enabled: true
          ifindex_1082: 285278473
          ifindex_1012: 268503296
        - pon_id: 10
          enabled: true
          ifindex_1082: 285278474
          ifindex_1012: 268503552
        - pon_id: 11
          enabled: true
          ifindex_1082: 285278475
          ifindex_1012: 268503808
        - pon_id: 12
          enabled: true
          ifindex_1082: 285278476
          ifindex_1012: 268504064
        - pon_id: 13
          enabled: true
          ifindex_1082: 285278477
          ifindex_1012: 268504320
        - pon_id: 14
          enabled: true
          ifindex_1082: 285278478
          ifindex_1012: 268504576
        - pon_id: 15
          enabled: true
          ifindex_1082: 285278479
          ifindex_1012: 268504832
        - pon_id: 16
          enabled: true
          ifindex_1082: 285278480
          ifindex_1012: 268505088

    - slot: 2
      type: "GTGH"  # 16 PON
      pons:
        - pon_id: 1
          enabled: true
          ifindex_1082: 285278721
          ifindex_1012: 268566784
        - pon_id: 2
          enabled: true
          ifindex_1082: 285278722
          ifindex_1012: 268567040
        - pon_id: 3
          enabled: true
          ifindex_1082: 285278723
          ifindex_1012: 268567296
        - pon_id: 4
          enabled: true
          ifindex_1082: 285278724
          ifindex_1012: 268567552
        - pon_id: 5
          enabled: true
          ifindex_1082: 285278725
          ifindex_1012: 268567808
        - pon_id: 6
          enabled: true
          ifindex_1082: 285278726
          ifindex_1012: 268568064
        - pon_id: 7
          enabled: true
          ifindex_1082: 285278727
          ifindex_1012: 268568320
        - pon_id: 8
          enabled: true
          ifindex_1082: 285278728
          ifindex_1012: 268568576
        - pon_id: 9
          enabled: true
          ifindex_1082: 285278473
          ifindex_1012: 268503296
        - pon_id: 10
          enabled: true
          ifindex_1082: 285278474
          ifindex_1012: 268503552
        - pon_id: 11
          enabled: true
          ifindex_1082: 285278475
          ifindex_1012: 268503808
        - pon_id: 12
          enabled: true
          ifindex_1082: 285278476
          ifindex_1012: 268504064
        - pon_id: 13
          enabled: true
          ifindex_1082: 285278477
          ifindex_1012: 268504320
        - pon_id: 14
          enabled: true
          ifindex_1082: 285278478
          ifindex_1012: 268504576
        - pon_id: 15
          enabled: true
          ifindex_1082: 285278479
          ifindex_1012: 268504832
        - pon_id: 16
          enabled: true
          ifindex_1082: 285278480
          ifindex_1012: 268505088


olts:
  - name: "c320-scmnet"
    snmp:
      version: "2c"
      host: "192.168.88.49"
      port: 161
      community: "scmsnmprw"
      timeout_ms: 2000
      retries: 1

  - name: "c320-pcnet"
    snmp:
      version: "2c"
      host: "103.156.75.215"
      port: 1191
      community: "pcnetrw"
      timeout_ms: 2000
      retries: 1

  - name: "c320-triamed"
    snmp:
      version: "2c"
      host: "103.156.75.217"
      port: 2161
      community: "triamedrw"
      timeout_ms: 2000
      retries: 1
